Synthetixio/js-monorepo

packages/wei/__tests__/wei.ts
packages/wei/babel.config.json
packages/wei/package-lock.json
packages/wei/package.json
packages/wei/src/index.ts
packages/wei/src/wei.ts
packages/wei/tsconfig.json
packages/wei/tsconfig.node.json

`Wei` is a simple wrapper around the ethers `BigNumber` which provides features for conversion,
decimal scaling, and math, normally expected in a regular BigNumber library. The math is
intended to mimic as closely as possible the same operations which actually occur within
the EVM, and to be lightweight as well.
For more advanced math operations, Wei uses `Big.js` under the hood. This can be changed.
Quick samples:
Making a new `Wei` instance:
```
import { wei } from '@synthetixio/wei';
// constructing "42100000000000000000"
const numba = wei(42.1);
const strig = wei('42.1');
const plainbn = wei(new ethers.BigNumber('42100000000000000000'));
// numba == strig == plainbn
// using other than default `Wei` units
const satoshis = wei(1, 8);
```
Math:
```
const a = wei(1.2);
const b = …
```

add wei package

---

packages/contracts-interface/package-lock.json
packages/data/package-lock.json
packages/optimism-networks/package-lock.json
packages/providers/package-lock.json
packages/queries/package-lock.json
packages/transaction-notifier/package-lock.json
packages/wei/package-lock.json
packages/wei/package.json
packages/wei/src/index.ts

this causes an error on recent releases because we are now building the `webpack` version of the module as well, which fails to export due to the `package.json` specification.

fixes for wei not exporting the `wei` function

---

packages/queries/package.json
packages/queries/webpack.config.js

webpack has an "externals" option to mark certain npm modules as resolved from browser
in addition, specify the "module" option for webpack projects which can import without
the need for the browser version

fix queries browser deps

---

.github/workflows/main.yml
lerna.json
packages/data/package.json

this will allow for easier testing of monorepo changes with existing repos.
It will be p ushed using a npm `tag` to prevent confusing of accidentally
using development releases

automatically push testing release to npm repo

---

packages/data/__tests__/queries.test.ts
packages/data/queries/rateUpdates/parse.ts
packages/data/src/constants.ts
packages/data/src/index.ts

- Adding the endpoint for L2 Kovan rate updates
- This will allow Kwenta to render the rates chart for rates on L2 Kovan

feat(data): Add L2 kovan rates to rateUpdates

---

packages/data/__tests__/queries.test.ts
packages/data/queries/rateUpdates/parse.ts
packages/data/src/index.ts

This reverts commit ebbf46b1d2bc6f531f212153353cd573d911c3d9.

Revert "feat: point L2 mainnet rates queries to L1 subgraphs (#51)"

---

packages/queries/src/queries/walletBalances/useTokensBalancesQuery.ts

We were converting all currency balances to wei with the default 18 decimal standard. This fixes the conversation for tokens that don't use 18 decimals (ie. USDC, USDT)

fix(queries): added decimal argument to wei conversion in token balance query

---

packages/queries/package.json
packages/queries/src/queries/synths/useTotalIssuedSynthsExcludingEtherQuery.ts

In the latest release 2.48.0 there were modifications to ```useTotalIssuedSynthsExcludingEtherQuery``` as seen here https://github.com/Synthetixio/synthetix/blob/master/contracts/interfaces/ISynthetix.sol#L42
This PR updates the function call so it gets the right value for display debt needed on the dApps

update useTotalIssuedSynths query

---

packages/data/webpack.config.js

Useful for browser-based projects like this codepen: https://codepen.io/justinjmoses/full/EzoEbM 
The library field copies the named `library` parameter to `window` for ease of use.

Adding library target to data package

---

packages/data/codegen.yml
packages/data/src/constants.ts
packages/data/src/index.ts

rates subgraph has been replaced entirely with `exchanges`. This updates the queries
library to only use exchanges endpoints.

deprecate rates subgraph

---

packages/optimism-networks/src/constants.ts
packages/optimism-networks/src/types.ts
packages/queries/src/queries/ovm-bridge/useGetBridgeDataQuery.ts

Metamask throws an error when trying to use optimism via the current config.

[optimism-networks] fix: remove 'fraudProofWindow' from optimism network config

---

.github/workflows/main.yml
.github/workflows/updateDependency.yml

* `main` pipeline will not run unless attached to a PR or on main branch (might want to omit main branch as well but that comes later)
* `updateDependency` pipeline updated to `workflow_dispatch` which allows for triggering update by just clicking a button on GitHub UI
because of the second update, `updateDependency` now takes 2 parameters, one for the upstream version number, and one for the monorepo
new version. If no version is supplied, the version will be automatically bump ed by lerna

new features for CI

---

packages/queries/codegen.js
packages/queries/src/mutations/useEVMTxn.test.ts
packages/queries/src/mutations/useEVMTxn.ts

I think we only need to update the `gasLimit` when the `to` address changes?
With the previous implementation we were in an infinity loop. Fetching gas meant that the transaction got its `data` and `value` set. When it finished those properties gets set to null causing the useEffect to be triggered again.

Avoid infinity loop

---

packages/queries/src/index.ts

after implementing downstream, it has become apparent that resolving and passing the `subgraphUrl` every
time is not a very good pattern. As the subgraph data must be injected into the context for the queries library anyway, this will
allow for calling of subgraph functions directly from `useSynthetixQueries` with the first `subgraphUrl` argument
mapped with the url of the corresponding subgraph.

map subgraph functions with context same as rest of query library

---

packages/wei/__tests__/wei.ts
packages/wei/src/wei.ts

```
// Example serialization for wei(100)
"100.000000000000000000"
// Example serialization for wei(100, 0, true)
"100"
```

feat: serialize wei as string instead of hex

---

packages/queries/src/queries/debt/useGetDebtDataQuery.ts

`targetThreshold` is returned but missing in type signature

Include targetThreshold in WalletDebtData

---

package-lock.json
packages/providers/package-lock.json
packages/providers/package.json
packages/providers/src/index.ts
packages/providers/src/types.ts

Clem did that for Aelin and was encouraging us to do the same. I thought that it would be a good addition to the provider package.
Code used in Aelin
```
const handleSwitchChain = useCallback(async () => {
if (!provider || !network?.id || !walletAddress) return;
const web3Provider = provider as ethers.providers.Web3Provider;
if (!web3Provider.provider || !web3Provider.provider.request) return;
const newNetworkId = getCorrespondingNetwork(network?.id, isOVM);
const formattedChainId = ethers.utils.hexStripZeros(BigNumber.from(newNetworkId).toHexString());
await web3Provider.provider.request({
method: 'wallet_switchEthereumChain',
params: [{ chainId: formattedChainId }],
});
}, [isOVM, provider, network?.id, walletAddress]);
```
⚠️ ⚠️ ⚠️
Made some test and it seems only the Coinbase wallet …

add handleSwitchChain func

---

package-lock.json
packages/queries/src/queries/staking/useGlobalStakingInfoQuery.ts
packages/queries/src/queries/staking/useLockedSnxQuery.ts

In staking we only care about lockedValue from `useGlobalStakingInfoQuery`. I depricated that hook and added a simpler `useLockedSnxQuery`.
Also upgrading `codegen-graph-ts`

updated subgraph url

---

packages/queries/src/queries/staking/useSNXData.ts

The two holder queries in this hook will generate 16 request since the graph need to paginate every 1000 items.
The number of holder should be fairly consistent so to avoid sending off 16 request frequently we cache it for one hour and disable refetching.
Also fetch the price and the total supply in parallel

Cache holders query

---

v2/components/CRatioHealthCard/CRatioHealthCard.cy.tsx
v2/components/CRatioHealthCard/CRatioProgressBar.tsx

Test and comment tries to explain, let me know if it doesn't make sense. I talked through this solution with jade
Before:
After:

Ensure liquidation and target labels dont overlap when c-ratio is relly large

---

v2/components/ExternalLink/ExternalLink.tsx
v2/components/Navigation/Navigation.tsx
v2/components/Navigation/package.json
v2/components/WalletModal/WalletModal.stories.tsx
v2/components/WalletModal/WalletModal.tsx
v2/components/WalletModal/index.ts
v2/components/WalletModal/package.json
v2/components/icons/AvatarIcon/AvatarIcon.tsx
v2/components/icons/AvatarIcon/index.tsx
v2/components/icons/CopyIcon/CopyIcon.tsx
v2/components/icons/CopyIcon/index.tsx
v2/components/icons/index.tsx
v2/lib/txnLink/txnLink.test.ts
v2/lib/txnLink/txnLink.ts
v2/lib/useSynthsBalances/useSynthsBalances.ts
v2/ui/translations/en.json
v2/ui/v2-components/Header/Header.tsx
yarn.lock

Some differences compared to the design, need to have a chart with Jade.. But at least a start 
Things to chat with Jade about:
- Icons, the design is using perps icons
- The description under the synth name, is currently not included. If we want we could use the description from here: https://github.com/Synthetixio/synthetix/blob/develop/publish/assets.json?
- "Connected with MetaMask" note, not sure how much value that adds and also not sure how easy it is to know what wallet is used
- Leaving out Delegated and Watch Wallet. I think we need designs for these. currently they opens in a modal. It would be a little weird to open a modal from a modal.
- How should this popup look when we're not connected? Should the Account menu item be hidden?
-  We will only show synths if you have any …

Wallet modal

---

v2/components/Burn/Burn.tsx
v2/lib/stakingCalculations/stakingCalculations.ts
v2/ui/translations/en.json

- Make sure unstaking amout gets set when clicking badges
- Display frontend error message rather than "Subtraction Overflow"

Burn fixes

---

v2/components/Navigation/Navigation.tsx
v2/components/WalletModal/WalletModal.tsx

- Navigate to home when disconnecting wallet
- Close modal when navigating to new page
- Dont display help menu item
- Link to guide
- Only display account when wallet is connected

Wallet fixes

---

v2/components/Burn/BurnHeader.tsx
v2/components/CRatioBanner/CRatioBanner.tsx
v2/components/CRatioBox/CRatioBox.tsx
v2/components/CRatioHealthCard/CRatioHealthCard.tsx
v2/components/CRatioHealthCard/CRatioProgressBar.tsx
v2/components/MainActionCards/MainActionCards.tsx
v2/components/MainActionCards/MainActionCardsList.tsx
v2/components/Mint/MintHeader.tsx
v2/components/SelfLiquidation/SelfLiquidation.tsx
v2/lib/getHealthVariant/getHealthVariant.test.ts
v2/lib/getHealthVariant/getHealthVariant.ts
v2/lib/useSelfLiquidationData/useSelfLiquidationData.ts

The FeePool contract (where we claim) takes a threshold ( called `targetThreshold` on the `SystemSettings` contract) into account. If your c-ratio is below target but within the threshold you can claim. There's no threshold for liquidations.
We already fetched `targetThreshold` in the debtData hook. So this PR just make sure we take it into account in `getHealthVariant`

Target threshold

---

v2/components/UtilityCard/UtilityCard.stories.tsx
v2/lib/Constants/links.ts
v2/ui/constants/links.ts
v2/ui/content/V2Home.tsx
v3/ui/src/layouts/Default/Header.tsx

This PR updates any mentions of `https://kwenta.io` to the official, Kwenta endorsed URL `https://kwenta.eth.limo` URL, which hosts the decentralized Kwenta deployment.
`https://kwenta.io` is on its way to be deprecated, hence should be avoided if possible. For more information, see [KIP-22](https://kips.kwenta.io/kips/kip-22/).
Note that below file lines 44 resp. 47 add links to the long deprecated `shorting` page on Kwenta, which should probably be removed from the repository. These have not been touched by this commit.
https://github.com/Synthetixio/js-monorepo/blob/bc4a61b92d09bc01e03750a649989485ba05d7bb/v2/ui/constants/routes.ts#L44-L46

update kwenta to official url

---

v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.tsx

Maintain card needs to take `targetThreshold` into account
Before:
After:

Maintain button threshold

---

v2/components/EpochPrice/EpochPrice.tsx
v2/components/SelfLiquidation/SelfLiquidation.cy.tsx
v2/components/SelfLiquidation/SelfLiquidation.tsx
v2/components/UnflagOptions/UnflagOptions.tsx
v2/ui/Routes.tsx
v2/ui/content/V2Burn.tsx
v2/ui/content/V2Mint.tsx
v2/ui/content/V2Unflag.tsx
v2/ui/package.json
v2/ui/translations/en.json
yarn.lock

Main thing is to use liquidation penalty data to render correct amount

Fix display amount in unflag and self-liquidate

---

v3/lib/useAllowance/index.ts
v3/lib/useAllowance/package.json
v3/lib/useAllowance/useAllowance.ts
v3/ui/package.json
v3/ui/src/components/accounts/Position/useManagePosition.ts
v3/ui/src/hooks/useApprove.ts
v3/ui/src/hooks/useApproveCall.ts
yarn.lock

- Add useAllowance hook
- Fix types in useApprove
A first step to replacing wagmi in useApprove. We haven't done any mutation queries without wagmi so yet, so a little bit of work required.

Add useAllowance hook

---

v3/ui/assert-deployment.js

We might want to use something more sophisticated, but this is useful as if deployments continues being flakey

A temporary script to for catching deployment problems

---

v3/ui/src/pages/Home/Home.tsx
v3/ui/src/pages/Home/VaultRow.tsx

- Show issuance ration and liquidation ratio rather than performance
- Show `-` insted of `0` when no position
- Make home page responsive. The chakra table doesn't have support for proper responsiveness so just making it scrollable for now
- Skeletons for home page

Home page improvements

---

v2/cypress/cypress/e2e/loans.e2e.js
v2/ui/containers/Loans/Loans.tsx
v2/ui/sections/loans/components/ActionBox/BorrowSynthsTab/BorrowSynthsTab.tsx

Handle loans being disabled.
Loans wont be enabled until v3. And in v3 it will work very differently. Maybe I should remove the test rather than skipping it?

Handle loans disabled

---

v3/components/CollateralTypeSelector/CollateralTypeSelector.tsx
v3/lib/useCollateralTypes/useCollateralTypes.ts
v3/ui/src/pages/AccountPositionPage/DepositingStats.tsx
v3/ui/src/pages/Home/VaultRow.tsx
v3/ui/src/pages/deposit/Deposit.tsx
v3/ui/src/pages/pools/CollateralSection.tsx

- Add a displaySymbol property to collateral type that ensures WETH is displayed as ETH
- Still keeping WETH in url
- Only updated pages that dont have a refactor incoming

Add display symbol

---

v2/components/Burn/Burn.tsx

- Dont round numbers for preset.
- Send whole usd balance when `debtBalance` preset is active (see comment)
- Allow 18 dp in input field

V2 burn fixes

---

v3/ui/src/pages/pools/CollateralSection.tsx
v3/ui/src/pages/pools/MarketSection.tsx
v3/ui/src/pages/pools/pool.tsx

- Max debt not a seperate column any more
- Vault C-ratio added

More pool updates

---

v3/components/NumberInput/NumberInput.tsx
v3/lib/ManagePositionContext/ManagePositionContext.tsx
v3/lib/ManagePositionContext/index.ts
v3/lib/ManagePositionContext/package.json
v3/lib/useUSDProxy/index.ts
v3/lib/useUSDProxy/package.json
v3/lib/useUSDProxy/useUSDProxy.ts
v3/ui/package.json
v3/ui/src/App.tsx
v3/ui/src/pages/AccountPositionPage/useManagePosition.ts
v3/ui/src/pages/Manage/Borrow.tsx
v3/ui/src/pages/Manage/Manage.tsx
v3/ui/src/pages/Manage/ManageActions.tsx
v3/ui/src/pages/Manage/Repay.tsx
v3/ui/src/pages/Manage/Withdraw.tsx
yarn.lock

This adds Borrow action for manage screen, it's fully working.  Deposit, Withdraw and Repay should be easy to add if we're happy with the structure.
I tried to minimize prop drilling, since it would be quite deep. I do this by relying on query hooks like usual but I also opted to create a `ManagePositionContext`. This context hold state for `debtChange` and `collateralChange`. The 
`useManagePosition` hook is called quite high up in the tree, but since it's reads debtChange and collateralChange from context, it should be easy to add the "Additional Action" ui.
This will also make it easy to create the "changes in debt, collateral and c-ratio" boxes. 
```ts
const { debtChange, collateralChange } = useContext(ManagePositionContext);
const collateralType = …
```

Manage borrow, repay & withdraw

---

v2/components/BurnStats/BurnStats.tsx
v2/components/BurnStats/package.json
v2/components/RewardsItem/Fees.tsx
v2/components/RewardsItem/package.json
v2/lib/useFeePoolData/useFeePoolData.ts
v2/lib/useFeesBurnedInPeriod/index.ts
v2/lib/useFeesBurnedInPeriod/package.json
v2/lib/useFeesBurnedInPeriod/useFeesBurnedInPeriod.test.ts
v2/lib/useFeesBurnedInPeriod/useFeesBurnedInPeriod.ts
v2/lib/useSynthetixContracts/index.ts
v2/lib/useSynthetixContracts/useSynthetixDebtShare.ts
yarn.lock

This fixes the burn amount. Still needs another PR for the APR calculation. 
The reason why this is needed is due to the global debt is shared between the networks. 
So we cant just check what was burned on the network you stake on. There's a burn on the other network too and that will affect the global debt.
See convo in staking-team for more context

Cross network burn

---

v2/lib/useFeesClaimed/package.json
v2/lib/useFeesClaimed/useFeesClaimed.tsx
v2/lib/useGetLifetimeRewards/package.json
v2/lib/useGetLifetimeRewards/useGetLifetimeRewards.tsx
v2/ui/content/DelegatePage.tsx
v2/ui/content/HistoryPage.tsx
v2/ui/content/MergeAccountsPage.tsx
v2/ui/package.json
v2/ui/sections/delegate/index.tsx
v2/ui/sections/history/Transactions/Transactions.tsx
v2/ui/sections/merge-accounts/common.ts
yarn.lock

- Remove incorrect state from Delegate and Merge Account page
- Move schedar release workaround to useFeesClaimed hook
- Use `useFeesClaimed` on the history page, so that rewards are showing up correctly

Clean up old pages

---

packages/queries/src/queries/escrow/useEscrowDataQuery.ts

If we try to migrate an escrow entry with amount = 0 it will fail on the optimism side

Only include vesting entries with amount bigger than 0

---

v2/components/Burn/Burn.tsx
v2/components/Mint/Mint.tsx
v2/components/Navigation/Navigation.tsx
v2/components/RewardsItem/ClaimRewardsBtn.tsx
v2/components/WalletModal/AuthorisedWallets.tsx
v2/ui/translations/en.json

- Add back some missing margin in header that was accidentally removed
- Ensure delegation popup closes when users click on setup Delegate link
- Mint and burn shows custom delegation missing message, like we do for some other cases when button is disabled.
- Claim show the delegation missing message in a tooltip, since we currently not displaying errors for claiming

Delegate qa

---

v2/components/MintOrBurnChanges/MintOrBurnChanges.tsx
v2/components/MintOrBurnChanges/package.json
v2/lib/stakingCalculations/stakingCalculations.test.ts
v2/lib/stakingCalculations/stakingCalculations.ts
yarn.lock

Fix calculation for changes from burn. Previously we tried to calculate escrowed snx, the calculation used was wrong. Now we instead fetch escrowedSnx.
So:
`const newTransferable = Math.max(collateral - escrowedSnx - newStakedAmountSnx, 0);`

Remove incorrect escrowed SNX. Just grab it from hook/contract

---

v2/ui/sections/debt/components/ManageTab/BuyHedgeTabOptimism.tsx
v2/ui/sections/debt/components/ManageTab/SellHedgeTabOptimism.tsx

I think I made a mistake when I removed slippage.. Prod shows 0 estimation.. this fixes that

Fix estimated amount and remove out of date tooltip

---

v2/perps-v2/perps-subgraph/generated/schema.ts
v2/perps-v2/perps-subgraph/schema.graphql
v2/perps-v2/perps-subgraph/src/calculations.ts
v2/perps-v2/perps-subgraph/src/futures.ts
v2/perps-v2/perps-subgraph/src/position-modified.ts
v2/perps-v2/perps-subgraph/src/trade-entities.ts
v2/perps-v2/perps-subgraph/tests/perpsV2-utils.ts
v2/perps-v2/perps-subgraph/tests/perpsV2.test.ts
v2/perps-v2/perps-subgraph/tests/position-modified.test.ts

This PR separates realized pnl from unrealized pnl. 
I also changes back types to `BigInt` from `BigDecimal`. We store all values with 18 decimals, so they are all ints. If we start storing values with `val / 1e18` we should change to BigDecimals.
I also made sure that netTransfers are up to date.
PNL Spec:
```
realisedPnl = fees.mul(-1) // funding is 0
unrealisedPnl = 0 
Avg entry price = current price
```
```
netTradePnl = gain/loss based on the trade size and avgEntryPrice (happy to share calc if interest)
realisedPnl = previousRealisedPnl.plus(netTradePnl).minus(fees).plus(netAccruedFundingSinceLastInteraction)
unrealised = (currentPrice - avgEntryPrice) * new size
```
```
realisedPnl = previousRealisedPnl.minus(fees).plus(netAccruedFundingSinceLastInteraction)
unrealisedPnl = …
```

Subgraph pnl

---

v2/perps-v2/perps-subgraph/generated/schema.ts
v2/perps-v2/perps-subgraph/schema.graphql
v2/perps-v2/perps-subgraph/src/historical-trade-stats.ts
v2/perps-v2/perps-subgraph/src/position-modified.ts
v2/perps-v2/perps-subgraph/tests/historical-trade-stats.test.ts
v2/perps-v2/perps-subgraph/tests/perpsV2-utils.ts

This adds a three new entities:
DailyMarketStats
DailyStats
CumulativeMarketStats
This should be enough to create most of the charts on the dashboard designs. 
We could also add:
Monthly stats 
MonhtlyMarket stats 
if we want to avoid aggregations on the frontend.

History trade stats

---

v2/perps-v2/perps-subgraph/generated/schema.ts
v2/perps-v2/perps-subgraph/schema.graphql
v2/perps-v2/perps-subgraph/src/historical-trade-stats.ts
v2/perps-v2/perps-subgraph/src/position-modified.ts
v2/perps-v2/perps-subgraph/tests/historical-trade-stats.test.ts
v2/perps-v2/perps-subgraph/tests/perpsV2-utils.ts
v2/perps-v2/perps-subgraph/tests/perpsV2.test.ts

This adds a three new entities:
`DailyMarketStats`
`DailyStats`
`CumulativeMarketStats`
This should be enough to create most of the charts on the dashboard designs.
We could also add:
Monthly stats
MonhtlyMarket stats
if we want to avoid aggregations on the frontend.
As I was working on historical stats I found some bugs a long the way:
- Dont update trades if tradesize is 0, this means it's not a trade.
- Correct initialMargin
- Correct update of fesByPositionModification

Historical trade stats

---

v2/perps-v2/perps-subgraph/src/futures.ts
v2/perps-v2/perps-subgraph/src/historical-trade-stats.ts
v2/perps-v2/perps-subgraph/tests/historical-trade-stats.test.ts

Make sure the fees on daily/cumulative entities gets the fee tracking updated from orders and liquidation. Perviously it only got updated from position modification events

Cumulative fees fix

---

v2/perps-v2/perps-subgraph/networks.json

https://contracts.synthetix.io/ovm/FuturesMarketManager 
Goes to: https://optimistic.etherscan.io/address/0xd30bdFd7e7a65fE109D5dE1D4e95F3B800FB7463
Contract was created at block 86524190: 
https://optimistic.etherscan.io/tx/0xe3fe83acbc21d7acbc70b6cc7360c63f7511dc737aa821f28aa62b592f3d58f8
This explains why new markets aren't showing up. We listen to `MarketAdded` event on an old unused `FuturesMarketManager` contract

Correct address and start block for FuturesMarketManager

---

v2/perps-v2/perps-subgraph/generated/schema.ts
v2/perps-v2/perps-subgraph/schema.graphql
v2/perps-v2/perps-subgraph/src/futures.ts
v2/perps-v2/perps-subgraph/src/liquidation.ts
v2/perps-v2/perps-subgraph/src/position-modified.ts
v2/perps-v2/perps-subgraph/src/trade-entities.ts
v2/perps-v2/perps-subgraph/subgraph.base.yaml
v2/perps-v2/perps-subgraph/tests/liquidation.test.ts
v2/perps-v2/perps-subgraph/tests/margin-transfer.test.ts
v2/perps-v2/perps-subgraph/tests/perpsV2.test.ts
v2/perps-v2/ui/src/components/Actions/AllActionsTable.tsx

- Before this change all trade entities was missing the relation to the orders.
We know have a new field on the OrderEntity called market order. If this is set to true, we expect the orderType to be null. Otherwise there should always be a relation from FuturesTrade to OrderEntity.
- Moved out liquidation and margin transfer tests. Matchstick doesn't have `only` feature for running tests, so it make sense to have things more split out
- When updating fee aggregation for keeper fees we only want that to happen if we have a trade entity.

Fix missing order trade relation

---

v3/lib/usePoolData/usePoolData.tsx
v3/theme/src/theme.ts
v3/ui/src/pages/Pool/CollateralSection.tsx
v3/ui/src/pages/Pool/MarketSection.tsx

No more crazy big numbers:
Tooltip explaining the calculations:

V3 pool info

---

v3/lib/usePoolData/usePoolData.tsx
v3/ui/src/App.tsx
v3/ui/src/pages/Pool/MarketSection.tsx

- Make sure market snapshots are sorted on time. 
- Chakra darkmode fixed (hopefully, cant reproduce locally)
- Percent formatted:
Before:
- Log out market data on row click

More pool page updates

---

v2/ui/containers/Connector/config.ts
v3/lib/useBlockchain/useBlockchain.tsx

I also enabled Goerli and Mainnet. Let me know if we still have a reason for keeping them hidden

Network fix

---

v2/components/EthGasPriceEstimator/EthGasPriceEstimator.tsx
v2/components/EthGasPriceEstimator/package.json
v2/lib/feeSuggestion/feeSuggestion.ts
v2/lib/feeSuggestion/index.ts
v2/lib/feeSuggestion/math.ts
v2/lib/feeSuggestion/package.json
v2/lib/feeSuggestion/utils.ts
v2/lib/useGasOptions/useGasOptions.ts
v2/lib/useGasPrice/package.json
v2/lib/useGasPrice/useGasPrice.ts
yarn.lock

The feeSuggestion module is heavily inspired by https://github.com/rainbow-me/fee-suggestions
That library have some hardcoded min and max that doesn't make sense for optimism. See: https://github.com/rainbow-me/fee-suggestions/blob/main/src/index.ts#L165
So I changed min/max a bit
That library is also a bit overkill in how it calculates `maxFeePerGas` per gas. It's using linear regression and sampling curves. Instead of doing that, this module calculates max by taking (previous baseFeePerGas * 2) + maxPriorityFeePerGas.
The calculation for `maxPriorityFeePerGas` I kept quite complex since that will affect what the user actually pay..
It's calculated based on the Exponential Moving Average (EMA) of the block rewards at the 15th, 30th, and 45th percentiles, after removing the outliers.
The …

Smarter priority fees

---

v2/components/Burn/Burn.tsx

We need to have burn to target enabled even when min stake time hasn't been reached.
Iniital state no error:
Error when using custom amount:
No error when burn to target is selected

Only block burning from min stake time if custom burning is used

---

v2/perps-v2/ui/src/components/Shared/Market/Market.tsx

Fixes the issue of currency icon being squished on mobile by setting an explicit width of 30px to the parent div

fix currency icon squish

---

v2/perps-v2/ui/src/index.tsx

@jmzwar @bachstatter Hotfix migrate react-query v3 to @tanstack/react-query v4

Fix migrate react-query v4

---

v2/perps-v2/ui/src/components/Liquidations/LiquidationsTable.tsx
v2/perps-v2/ui/src/components/Shared/Action/Action.tsx
v2/perps-v2/ui/src/components/Shared/Market/Market.tsx
v2/perps-v2/ui/src/hooks/useLiquidations.ts

@jmzwar Can you help me review this PR?
Specs: Add which side the position was that was liquidated (long / short) + Tx Hash
https://watcher.synthetix.io/liquidations
Note:
- Size is positive for longs, negative for shorts
- Color code: longs green, shorts red

Add position side at Liquidations page
