Synthetixio/js-monorepo

packages/contracts-interface/src/types.ts

Needed types for OVM chain IDs on kwenta

feat: NetworkID enums for ovm mainnet and kovan

---

packages/optimism-networks/src/constants.ts
packages/optimism-networks/src/types.ts

- replaced block explorer urls and added icon urls
https://discord.com/channels/413890591840272394/809129093605097554/827023689038954536

fix: optimism urls

---

package-lock.json
packages/contracts-interface/README.md
packages/contracts-interface/examples/.eslintrc
packages/contracts-interface/examples/signer-example.js
packages/contracts-interface/package.json

Adding signer example, updating readme.

Adding examples

---

packages/contracts-interface/package-lock.json
packages/contracts-interface/package.json
packages/data/package-lock.json
packages/data/package.json
packages/optimism-networks/package-lock.json
packages/optimism-networks/package.json
packages/providers/package-lock.json
packages/providers/package.json
packages/queries/package-lock.json
packages/queries/package.json
packages/transaction-notifier/package-lock.json
packages/transaction-notifier/package.json
packages/wei/package-lock.json
packages/wei/package.json

this way builds always succeeed no matter what your local bins are

fix package issues; fix commands to use node_modules binaries

---

packages/queries/src/index.ts

cache is detrimental now that we are using the useContext from react

fixes for queries context creation

---

packages/queries/__tests__/network.test.ts
packages/queries/package-lock.json
packages/queries/src/queries/network/useEthGasPriceQuery.ts
packages/queries/src/utils.ts

Extended our useEthGasPriceQuery to incorporate ovm gas querying

feat: added l2 gas query

---

packages/queries/src/mutations/useEVMTxn.ts
packages/queries/src/queries/walletBalances/useTokensBalancesQuery.ts

* fix small error in error parsing for `useEVMTxn`
* must supply walletAddress for useTokenBalancesQuery

small fixes

---

packages/queries/src/mutations/useContractTxn.ts
packages/queries/src/mutations/useEVMTxn.ts
packages/queries/src/mutations/useSynthetixTxn.ts
packages/queries/src/queries/ovm-bridge/useGetBridgeDataQuery.ts

some fixes for `useEVMTxn` bugs found while testing `queries` PR of `staking`

remove emitter, replace with raw ethers.js

---

packages/queries/__tests__/synths.test.ts
packages/queries/src/queries/gov/constants.ts
packages/queries/src/queries/gov/useProposalsQuery.ts
packages/queries/src/queries/synths/useSynthsTotalSupplyQuery.ts

In the Mirfak release, the old loans were deprecated. In our apps we still reference the old loans causing some errors to appear

remove old loans in queries and update test

---

.github/workflows/updateDependency.yml
package-lock.json
packages/contracts-interface/__tests__/index.test.ts
packages/data/__mocks__/snxPrice.ts
packages/data/queries/snxPrice/parse.ts
packages/queries/src/mutations/useEVMTxn.ts
packages/queries/src/queries/staking/useGlobalStakingInfoQuery.ts
packages/queries/src/queries/synths/useTotalIssuedSynthsExcludeOtherCollateralQuery.ts
packages/queries/src/queries/walletBalances/useTokensBalancesQuery.ts

sXAG no longer exists, switch to a more reliably included synth sETH instead

fix tests after upstream

---

packages/queries/src/mutations/useEVMTxn.ts

seems gas estimate err message is at err.data.message

fix(queries): correctly compute gas estimate errors

---

packages/contracts-interface/package-lock.json
packages/queries/package-lock.json
packages/queries/package.json

this release uses axios, which fixes queries from within the browser

update queries with latest version of graph codegen

---

package-lock.json
packages/contracts-interface/package-lock.json
packages/contracts-interface/package.json
packages/providers/package-lock.json
packages/providers/package.json
packages/queries/package-lock.json
packages/queries/package.json
packages/transaction-notifier/package-lock.json
packages/transaction-notifier/package.json
packages/wei/package-lock.json
packages/wei/package.json

Update ethers to latest version

---

packages/queries/src/mutations/useEVMTxn.ts

- No guarantee that message is the first key

Relax isFrameWalletError check.

---

packages/queries/src/queries/debt/useGetDebtDataQuery.ts

-  1 debt share does not always equal 1 dollar

Switch back to debtBalanceOf

---

.github/workflows/updateDependency.yml

This make sure we notify futures-keepers when there's a new release
Requires this to be merged:
https://github.com/Synthetixio/futures-keepers/pull/55

Notify futures-keepers when there's a new release

---

packages/queries/src/queries/delegate/constants.ts
packages/queries/src/queries/delegate/useGetAuthoriserWallets.ts
packages/queries/src/queries/delegate/useGetDelegateWallets.ts

Using the main subgraph
Make return types a bit more consistent

Use mainsubgraph to get delegated wallets

---

packages/queries/src/queries/liquidations/useGetLiquidationDataQuery.ts

Should not be merged until SIP-148 is live

Use new liquidator contract

---

packages/queries/src/abis/ElectionModule.json
packages/queries/src/queries/gov/constants.ts

- Update ABI
- Add period code constants

Minor gov updates

---

packages/wei/__tests__/wei.ts
packages/wei/package.json
packages/wei/src/wei.ts
yarn.lock

This pr switches out ethers for ethers submodules. No functional changes.

Use submodules for ethers dependencies

---

contracts/codegen.js

Slight change to the codegen process so we have name, address, source and abi in the one file. Also using proxy as currently setup in contract-interface.

hydrate codegen

---

v2/ui/content/theme.ts

Body's min height matches the viewport

---

v2/lib/txnReducer/index.ts
v2/lib/txnReducer/package.json
v2/lib/txnReducer/txnReducer.ts
v2/lib/useMintMutation/package.json
v2/lib/useMintMutation/useMintMutation.ts
yarn.lock

This will be reused in useBurnMutation too

Move txnreducer to package

---

v2/components/Burn/Burn.tsx
v2/components/Mint/Mint.tsx
v2/components/Mint/MintTransactionModal.tsx
v2/lib/stakingCalculations/stakingCalculations.test.ts
v2/lib/stakingCalculations/stakingCalculations.ts

Lets users specify susd on mint page. Based on #409

Mint inputs

---

v3/ui/src/components/accounts/StakingPositions/StakingPosition.tsx

- it's a bit annoying to remember to do this for every link, routing.  the better solution will be to create a new `LinkWithSearchParams` that is basically a passthrough to `Link` but with search params appended.

add search params to route

---

v3/ui/src/components/NetworkChain.tsx
v3/ui/src/utils/constants.ts

- infinite loop bug when on unsupported network

remove initial redundant check

---

v2/components/CRatioBox/CRatioBox.tsx
v2/components/CRatioHealthCard/CRatioProgressBar.tsx
v2/components/SelfLiquidation/SelfLiquidation.cy.tsx
v2/components/SelfLiquidation/SelfLiquidation.tsx
v2/components/SelfLiquidation/SwapLinks.stories.tsx
v2/components/SelfLiquidation/package.json
v2/components/SwapLinks/SwapLinks.cy.tsx
v2/ui/Routes.tsx
v2/ui/content/V2SelfLiquidation.tsx
v2/ui/translations/en.json
yarn.lock

Will wire up the button in next PR

Self liquidation page

---

v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.tsx

Dont render rewards button when just claimed

---

v2/components/SelfLiquidation/SelfLiquidation.cy.tsx
v2/components/SelfLiquidation/SelfLiquidation.tsx
v2/lib/useSelfLiquidationData/package.json
v2/lib/useSelfLiquidationData/useSelfLiquidationData.test.ts
v2/lib/useSelfLiquidationData/useSelfLiquidationData.ts
v2/ui/translations/en.json
yarn.lock

- Contract will revert with "Subtraction overflow error"
- Also add tests for the button states
- Show gas error if it exists

Dont call calculateAmountToFixCollateral when healthy c-ratio

---

v2/components/CRatioBanner/CRatioBanner.cy.tsx
v2/components/CRatioBanner/CRatioBanner.tsx
v2/components/CRatioBanner/package.json
v2/components/CountDown/CountDown.cy.tsx
v2/components/CountDown/CountDown.tsx
yarn.lock

- Dont render c-ratio-banner when user just claimed.
- Add tests

C ratio banner

---

v2/components/WalletModal/WalletModal.tsx
v2/lib/ContractContext/ContractContext.tsx
v2/ui/App.tsx
v2/ui/translations/en.json

Add wallet type

---

v2/components/WalletModal/WalletModal.stories.tsx
v2/components/WalletModal/WalletModal.tsx
v2/components/WalletModal/package.json
v2/lib/ContractContext/ContractContext.tsx
v2/lib/synthsByName/index.ts
v2/lib/synthsByName/package.json
v2/lib/synthsByName/synthsByName.ts
v2/ui/App.tsx
v2/ui/translations/en.json
yarn.lock

Synth desc

---

v2/components/Navigation/Navigation.tsx
v2/components/Navigation/package.json
v2/components/WalletModal/WalletModal.tsx
v2/ui/v2-components/Header/Header.tsx
yarn.lock

Display ens if available 

---

v2/ui/components/BannerManager/BannerManager.tsx
v2/ui/constants/links.ts
v2/ui/constants/storage.ts
v2/ui/translations/en.json

NO READY TO MERGE: Add kwenta banner

---

v2/components/Burn/BurnHeader.tsx
v2/components/CRatioBanner/CRatioBanner.tsx
v2/components/CRatioHealthCard/CRatioHealthCard.cy.tsx
v2/components/CRatioHealthCard/CRatioHealthCard.tsx
v2/components/CRatioHealthCard/CRatioProgressBar.tsx
v2/components/CRatioHealthPercentage/CRatioHealthPercentage.stories.tsx
v2/components/CRatioHealthPercentage/CRatioHealthPercentage.tsx
v2/components/CRatioHealthPercentage/index.ts
v2/components/CRatioHealthPercentage/package.json
v2/components/Mint/MintHeader.tsx
v2/components/SelfLiquidation/SelfLiquidation.tsx
yarn.lock

Some structure changes for CRatio for nicer Loading state + other style fixes for main page stuff.

Cratio loading + other minor fixes

---

v2/ui/Routes.tsx

Add back weth-snx pools page

---

v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.tsx

The colors got wrong after the refactor, fixed and added a test

Make sure Maintain button is orange/ red depending on c-ratio

---

v2/components/Navigation/Navigation.tsx
v2/components/Navigation/package.json
v2/ui/sections/shared/Layout/UserMenu/UserMenu.tsx
yarn.lock

Opt in button

---

v2/components/WalletModal/WalletModal.tsx

Png icons are up to date

---

v2/components/BoxLink/BoxLink.tsx
v2/components/Burn/Burn.tsx
v2/components/Burn/BurnHeader.tsx
v2/components/Mint/Mint.tsx
v2/components/Mint/MintHeader.tsx
v2/components/Navigation/Navigation.tsx

Mint burn responsive

---

v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.tsx

Stake btn when user have rewards and healthy

---

v2/components/Mint/Mint.tsx
v2/ui/translations/en.json

Mint should always be disabled when current c ratio is below target

---

v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.tsx
v2/components/MainActionCards/MainActionCardsList.tsx
v2/components/MainActionCards/package.json
v2/lib/stakingCalculations/stakingCalculations.test.ts
v2/lib/stakingCalculations/stakingCalculations.ts
v2/ui/translations/en.json
yarn.lock

- Add rewards available instead of snx price
- Collect card should have a special disable style and have the button visible (and disabled) when there are rewards to collect.

Rewards available

---

v2/components/Burn/Burn.tsx
v2/ui/content/V2Home.tsx

Also a link update for the help button

We do not require a sUSD balance to calculate max | target

---

v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.stories.tsx
v2/components/MainActionCards/MainActionCards.tsx
v2/ui/content/theme.ts
v2/ui/translations/en.json

- Dont show burn badge when rewards are claimed
- Always make sure users who are staking can go to the claim page
- Update tests
- Add a story for each test case

Maincard updates

---

v2/components/Navigation/Navigation.tsx
v2/components/WalletModal/WalletModal.tsx
v2/components/WalletModal/package.json
v2/lib/useDSnxBalance/useDSnxBalance.ts
v2/ui/sections/shared/Layout/UserMenu/UserMenu.tsx
v2/ui/translations/en.json
yarn.lock

This is based on the wallet PR, #485. Please look at that first 
When activating delegate mode go back to old ui and make sure delegate mode popup is open

Delegate mode

---

v2/components/Burn/Burn.tsx

Display correct burn amount

---

v2/components/Burn/Burn.tsx
v2/components/CRatioBox/CRatioBox.tsx
v2/components/EpochPrice/EpochPrice.tsx
v2/components/Mint/MintHeader.tsx
v2/components/MintOrBurnChanges/MintOrBurnChanges.tsx
v2/ui/translations/en.json

Tooltip content changes

---

v2/components/Burn/Burn.tsx
v2/components/Burn/BurnLinks.tsx
v2/components/Mint/Mint.tsx
v2/components/Mint/MintLinks.tsx
v2/components/icons/DebtPoolIcon/DebtPoolIcon.tsx
v2/ui/content/V2Home.tsx
v2/ui/sections/debt/components/ManageTab/BuyHedgeTabOptimism.tsx
v2/ui/sections/debt/components/ManageTab/HedgeTabMainnet.tsx
v2/ui/sections/debt/components/ManageTab/SellHedgeTabOptimism.tsx
v2/ui/translations/en.json

Links to manage debt

---

v2/components/CRatioBox/CRatioBox.cy.tsx
v2/components/CRatioBox/CRatioBox.tsx
v2/components/CRatioProgressBar/CRatioProgressBar.cy.tsx
v2/components/CRatioProgressBar/CRatioProgressBar.tsx
v2/components/SelfLiquidation/SelfLiquidation.cy.tsx
v2/lib/getHealthVariant/getHealthVariant.ts
v2/ui/content/theme.ts
v2/ui/translations/en.json

Burn max UI updates

---

v2/components/WalletBalances/TableComponents.tsx
v2/components/WalletBalances/WalletBalances.tsx

Align cols and remove top border on th

---

v2/components/UnflagOptions/UnflagOptions.cy.tsx
v2/components/UnflagOptions/UnflagOptions.stories.tsx
v2/components/UnflagOptions/UnflagOptions.tsx
v2/components/UnflagOptions/package.json
v2/ui/translations/en.json
yarn.lock

Resolves this QA feedback:
https://www.notion.so/7c6c105bbd36423196c86ac5a2f0e690?v=3caeff50526d41fb95e9e4dc000a32af&p=70491ce8e3ba4bc98cbc0b20ae32934d&pm=s

Unflag and liq updates

---

v2/components/RewardsItem/ClaimRewardsBtn.cy.tsx
v2/components/RewardsItem/ClaimRewardsBtn.tsx

- Should not be disabled when variant isn't success

Add test and fix claim button.

---

v2/components/RewardsItem/RewardsItem.tsx
v2/lib/useRewardsAvailable/useRewardsAvailable.ts

Dont display 0 when claimed

---

v2/components/RewardsItem/ClaimLiquidationBtn.tsx
v2/components/RewardsItem/RewardsItem.tsx
v2/cypress/cypress/e2e/home.e2e.js

liquidation threshold of 0.01 to claim

---

v3/subgraphs/goerli/generated/schema.ts
v3/subgraphs/goerli/schema.graphql
v3/subgraphs/goerli/src/core.ts
v3/subgraphs/goerli/tests/core.test.ts

Fix a bug an some refactors. 
In general the current market implementation just gives us current value, which we could get from contracts instead. 
It would be a lot of requests though, so gonna think about this a bit more..
What we definitely need is some kinda a market snapshot with a date so we can see historical values

Market withdrawn bug

---

v2/components/StatBox/StatBox.tsx
v2/components/WalletLayout/WalletLayout.tsx

Some improvements for wallet page on mobile

---

.github/workflows/updateDependency.yml

Remove staking and add perps-keeper.

Update deps action

---

v3/ui/package.json
v3/ui/src/components/accounts/Deposit/index.tsx
v3/ui/src/components/accounts/Position/Manage/Deposit.tsx
v3/ui/src/hooks/useDeposit.ts
v3/ui/src/hooks/useMulticall.ts
v3/ui/src/hooks/useTokenBalance.ts
v3/ui/src/hooks/useWrapEth.ts
v3/ui/src/pages/accounts/Account.tsx
yarn.lock

Note that the minimum amount of ETH to deposit is 1 ETH

Fix depositing weth

---

v3/lib/useEthPrice/index.ts
v3/lib/useEthPrice/package.json
v3/lib/useEthPrice/useEthPrice.ts
v3/lib/useGasOptions/package.json
v3/lib/useGasOptions/useGasOptions.test.ts
v3/lib/useGasOptions/useGasOptions.ts
yarn.lock

Adds a hook for getting the ETH price. This assumes that WETH will always be used as collateral. Which I think is reasnable

Use eth price

---

v3/components/Balance/Balance.tsx
v3/components/Balance/package.json
v3/lib/useBalance/index.ts
v3/lib/useBalance/package.json
v3/lib/useBalance/useBalance.ts
v3/ui/package.json
v3/ui/src/components/NetworkChain.tsx
v3/ui/src/components/NetworkController.tsx
v3/ui/src/components/accounts/Deposit/DepositForm.tsx
v3/ui/src/components/accounts/Deposit/index.tsx
v3/ui/src/components/accounts/Permissions/index.tsx
v3/ui/src/components/accounts/Position/Manage/Burn.tsx
v3/ui/src/components/accounts/Position/Manage/Custom.tsx
v3/ui/src/components/accounts/Position/Manage/Deposit.tsx
v3/ui/src/components/accounts/Position/Manage/Withdraw.tsx
v3/ui/src/components/accounts/Position/Rewards/Rewards.tsx
v3/ui/src/components/accounts/Position/Rewards/RewardsDistributor.tsx
v3/ui/src/components/accounts/Position/Rewards/RewardsDistributorTitle.tsx
v3/ui/src/components/shared/Address.tsx
v3/ui/src/components/shared/TransactionReview/MultipleTransactionReview.tsx
v3/ui/src/hooks/useContractEvent.tsx
v3/ui/src/hooks/useMulticall.ts
v3/ui/src/hooks/useTokenBalance.ts
v3/ui/src/pages/teleporter/Teleporter.tsx
yarn.lock

- Use `@snx-v3/useBlockchain` in more places rather than `wagmi`
- Add useBalance hook without wagmi
- Fix some type errors
- Explicitly ignore some type errors
- Enable typechecks again

Use balanace ngmi

---

v3/components/CollateralTypeSelector/CollateralTypeSelector.tsx
v3/lib/useParams/index.ts
v3/lib/useParams/package.json
v3/lib/useParams/useParams.ts
v3/theme/src/theme.ts
v3/ui/package.json
v3/ui/src/App.tsx
v3/ui/src/components/accounts/Deposit/DepositForm.tsx
v3/ui/src/components/accounts/Deposit/PercentBadges.tsx
v3/ui/src/components/accounts/Deposit/index.tsx
v3/ui/src/components/accounts/DepositingNav.tsx
v3/ui/src/components/accounts/Permissions/PermissionsEditor.tsx
v3/ui/src/components/accounts/Permissions/TransferOwnership.tsx
v3/ui/src/components/accounts/Permissions/index.tsx
v3/ui/src/pages/accounts/AcceptNomination.tsx
v3/ui/src/pages/accounts/Account.tsx
v3/ui/src/pages/accounts/LiquidityPosition.tsx
v3/ui/src/pages/deposit/Deposit.tsx
v3/ui/src/pages/deposit/index.tsx
v3/ui/src/pages/home/VaultRow.tsx
v3/ui/src/pages/home/home.tsx
v3/ui/src/pages/pools/AccountVaultCollateral.tsx
v3/ui/src/pages/pools/CollateralSection.tsx
v3/ui/src/pages/pools/MarketSection.tsx
v3/ui/src/pages/pools/PoolHeader.tsx
yarn.lock

Builds on top of #615. 
- Adds deposit.
- Also some fixes for the home page

Deposit page

---

v3/ui/src/pages/deposit/Deposit.tsx

Mobile styles deposit page

---

v3/components/BorderBox/BorderBox.tsx
v3/components/BorderBox/index.ts
v3/components/BorderBox/package.json
v3/ui/package.json
v3/ui/src/pages/Home/Home.tsx
v3/ui/src/pages/Home/VaultRow.tsx
v3/ui/src/pages/deposit/Deposit.tsx
v3/ui/src/pages/pools/CollateralSection.tsx
v3/ui/src/pages/pools/MarketSection.tsx
yarn.lock

TBD what goes into the third box

Home page updates

---

v3/ui/src/components/accounts/Deposit/DepositForm.tsx

Style ETH collateral according to designs

---

v3/ui/src/pages/pools/MarketSection.tsx

- Correctly calculate allocation
- Hide max debt for now. Needs some more though, ticket created: https://www.notion.so/7c6c105bbd36423196c86ac5a2f0e690?v=3caeff50526d41fb95e9e4dc000a32af&p=3520879efe654ed08dbedcea00b3f55f&pm=s

Pool page allocation

---

v3/lib/validatePosition/validatePosition.ts
v3/ui/src/components/accounts/Deposit/DepositModal.tsx

- So liquidityPositions is undefined

Fix deposit new account

---

v3/components/NumberInput/NumberInput.tsx
v3/ui/src/components/accounts/Deposit/DepositForm.tsx
v3/ui/src/components/accounts/Deposit/DepositModal.tsx

Styles NumberInput and uses it in deposit form.
Also use container pattern for Deposit Form

Deposit form wei

---

v3/lib/useUSDProxy/index.ts
v3/lib/useUSDProxy/package.json
v3/lib/useUSDProxy/useUSDProxy.ts
v3/ui/package.json
v3/ui/src/pages/Manage/ManageActions.tsx
v3/ui/src/pages/Manage/Repay.tsx
v3/ui/src/pages/Manage/Withdraw.tsx
yarn.lock

Withdraw have some slightly more complicated logic to figure out max. I've added comment to explain the calculation and a tooltip instructing the users that they need to repay the debt to be able to withdraw everything

Add withdraw

---

v3/lib/useUSDProxy/index.ts
v3/lib/useUSDProxy/package.json
v3/lib/useUSDProxy/useUSDProxy.ts
v3/ui/package.json
v3/ui/src/pages/AccountPositionPage/useManagePosition.ts
v3/ui/src/pages/Manage/ManageActions.tsx
v3/ui/src/pages/Manage/Repay.tsx
v3/ui/src/pages/Manage/Withdraw.tsx
yarn.lock

Based on #655 
Adds repay ui fully hooked up

Manage repay

---

v3/lib/useLiquidityPosition/useLiquidityPosition.ts
v3/lib/validatePosition/validatePosition.ts
v3/ui/src/pages/Home/VaultRow.tsx
v3/ui/src/pages/Manage/ManageActions.tsx
v3/ui/src/pages/Manage/ManageStats.tsx

Based on #663.
Ensure c-ratio is in decimal form like issuance and liquidation ratio

Cratio should be in decimal

---

v3/lib/useLiquidityPosition/useLiquidityPosition.ts
v3/lib/validatePosition/validatePosition.ts
v3/ui/src/pages/Home/VaultRow.tsx
v3/ui/src/pages/Manage/Manage.tsx
v3/ui/src/pages/Manage/ManageActions.tsx
v3/ui/src/pages/Manage/ManageStats.tsx

Manage position changes

---

v3/lib/useLiquidityPosition/useLiquidityPosition.ts
v3/lib/validatePosition/validatePosition.ts
v3/ui/package.json
v3/ui/src/pages/Home/VaultRow.tsx
v3/ui/src/pages/Manage/Manage.tsx
v3/ui/src/pages/Manage/ManageActions.tsx
v3/ui/src/pages/Manage/ManageStats.tsx
yarn.lock

- If you can borrow ->  show borrow
- If you 10% to liquidation ratio -> show repay
- Other wise -> show deposit

Default manage action

---

v3/lib/validatePosition/validatePosition.test.ts
v3/lib/validatePosition/validatePosition.ts

Adds tests for `validatePosition`
Found one bug related to withdrawals and some minor improvements

Validate position tests

---

v3/lib/useDeposit/index.ts
v3/lib/useDeposit/package.json
v3/lib/useDeposit/useDeposit.tsx
v3/lib/useGasOptions/useGasOptions.test.ts
v3/lib/useGasOptions/useGasOptions.ts
v3/lib/useGasPrice/useGasPrice.ts
v3/ui/package.json
v3/ui/src/components/accounts/Deposit/DepositModal.tsx
v3/ui/src/pages/Manage/Withdraw.tsx
v3/ui/src/pages/Manage/useManagePosition.ts
yarn.lock

Added a `useDeposit` hook that use `CoreProxy.multicall` without wagmi

Use deposit

---

v3/lib/useDeposit/package.json
v3/lib/useDeposit/useDeposit.tsx
v3/lib/useGasOptions/package.json
v3/lib/useGasOptions/useGasOptions.test.ts
v3/lib/useGasOptions/useGasOptions.ts
v3/lib/useGasSpeed/GasSpeedContext.tsx
v3/lib/useGasSpeed/index.ts
v3/lib/useGasSpeed/package.json
v3/lib/useRepay/package.json
v3/lib/useRepay/useRepay.tsx
v3/ui/package.json
v3/ui/src/index.tsx
yarn.lock

Add useGasSpeed hook. Can later build ui for users to adjust it

Use gas speed

---

v2/ui/content/V2Home.tsx

eth limo banner

---

v3/cypress/cypress/e2e/Pool - Not Connected.e2e.js
v3/ui/src/pages/pools/CollateralSection.tsx
v3/ui/src/pages/pools/MarketSection.tsx

E2E Pool page

---

v2/components/MainActionCards/MainActionCardsList.tsx
v2/components/MainActionCards/package.json
v2/lib/stakingCalculations/stakingCalculations.test.ts
v2/lib/stakingCalculations/stakingCalculations.ts
v2/lib/useGetUpcomingRewards/useGetUpcomingRewards.ts
v2/lib/useRewardsAvailable/useRewardsAvailable.ts
v2/ui/translations/en.json
yarn.lock

Make sure homepage doesn't include sUSD rewards

Sip 255 homepage updates

---

v2/ui/constants/dhedge.ts
v2/ui/sections/debt/components/ManageTab/BuyHedgeTabOptimism.tsx
v2/ui/sections/debt/components/ManageTab/HedgeTabMainnet.tsx
v2/ui/sections/debt/components/ManageTab/SellHedgeTabOptimism.tsx

Dsnx slippage

---

v2/perps-v2/ui/src/components/Positions/PositionsTable.tsx
v2/perps-v2/ui/src/components/Shared/Currency/Currency.tsx
v2/perps-v2/ui/src/components/Shared/Funding/Funding.tsx
v2/perps-v2/ui/src/components/Shared/MarginTransfer/MarginTransfer.tsx
v2/perps-v2/ui/src/components/Shared/MarkPrice/MarkPrice.tsx
v2/perps-v2/ui/src/components/Shared/NetValue/NetValue.tsx
v2/perps-v2/ui/src/components/Shared/PnL/PnL.tsx
v2/perps-v2/ui/src/components/Shared/Size/Size.tsx
v2/perps-v2/ui/src/utils/numbers.ts

- Dollar amount for position size if primary number
- Margin Transfer only need to display one number, sUSD = $1
- numberWithCommas had some edgecasy bugs so moved to Intl.NumberFormat

Number fixes

---

v2/perps-v2/ui/package.json
v2/perps-v2/ui/src/hooks/usePositions.ts
v2/perps-v2/ui/webpack.config.js
yarn.lock

Instead of 2 * number of positions api call, do one multicall.
It does get a lot harder to read, but I think it's worth it?

Do one api call for all positions data

---

v2/perps-v2/ui/codegen.ts
v2/perps-v2/ui/package.json
v2/perps-v2/ui/src/__generated__/graphql.ts
v2/perps-v2/ui/src/components/Actions/AccountActionsTable.tsx
v2/perps-v2/ui/src/hooks/useAction.test.ts
v2/perps-v2/ui/src/hooks/useActions.ts
yarn.lock

- Now using subgraphs data to generate nice action labels.
- ChatGPT generated tests and refactor 👯

Integrate subgraph

---

v2/components/MainActionCards/MainActionCards.tsx
v2/components/MainActionCards/MainActionCardsList.tsx
v2/components/MainActionCards/package.json
v2/ui/translations/en.json
yarn.lock

Add burned fees to collect card

---

v2/perps-v2/ui/package.json
v2/perps-v2/ui/src/components/Positions/PositionsTable.tsx
v2/perps-v2/ui/src/hooks/useActions.ts
v2/perps-v2/ui/src/hooks/usePositions.test.ts
v2/perps-v2/ui/src/hooks/usePositions.ts
v2/perps-v2/ui/src/index.tsx
v2/perps-v2/ui/src/queries/resolved.ts
v2/perps-v2/ui/src/types/positions.ts
v2/perps-v2/ui/src/utils/calculations.ts
yarn.lock

Replace react-query with a client side resolver.

move contract logic to resolver

---

v2/components/EarnStats/EarnStats.stories.tsx
v2/components/EarnStats/EarnStats.tsx
v2/components/EarnStats/package.json
v2/components/RewardsItem/Fees.tsx
v2/components/RewardsItem/RewardsItem.stories.tsx
v2/components/RewardsItem/RewardsItem.tsx
v2/lib/useClaimableRewards/index.ts
v2/lib/useClaimableRewards/package.json
v2/lib/useClaimableRewards/useClaimableRewards.ts
v2/lib/useGetUpcomingRewards/index.ts
v2/ui/content/V2Home.tsx
v2/ui/translations/en.json
yarn.lock

- apy -> apr
- Upcoming rewards -> Claimable rewards

Content changes

---

v2/perps-v2/ui/src/pages/Account.tsx

Remove position table

---

v2/perps-v2/ui/src/components/Positions/PositionsTable.tsx
v2/perps-v2/ui/src/hooks/usePositions.ts

I've started to update the mainnet subgraph. This make sure production works even though the synthetix package isn't released

Use new market data address

---

v2/perps-v2/ui/src/hooks/usePositions.ts

Synthetix released now so we can use the contract from v2/contracts

Use the contract rather than hardcoded address

---

v2/perps-v2/perps-subgraph/abis/PerpsV2Proxy.json
v2/perps-v2/perps-subgraph/generated/FuturesMarketManagerNew/PerpsV2Proxy.ts
v2/perps-v2/perps-subgraph/generated/FuturesMarketManagerOld/PerpsV2Proxy.ts
v2/perps-v2/perps-subgraph/generated/schema.ts
v2/perps-v2/perps-subgraph/generated/templates/PerpetualFuturesMarket/PerpsV2Proxy.ts
v2/perps-v2/perps-subgraph/prepare-codegen.js
v2/perps-v2/perps-subgraph/schema.graphql
v2/perps-v2/perps-subgraph/src/futures.ts
v2/perps-v2/perps-subgraph/subgraph.base.yaml

@bachstatter we can wait until a new version of the snx lib is released for the abis

New Position Flagged Event

---

v3/components/ExperimentalModal/ExperimentalModal.tsx
v3/components/ExperimentalModal/index.ts
v3/components/ExperimentalModal/package.json
v3/ui/package.json
v3/ui/src/App.tsx
yarn.lock

Made it only show up on non localhost host's so tests still pass
Spec:
https://www.notion.so/Add-aggressive-warning-to-v3-synthetix-io-c0424a64991b47008640ad01aebde97b?pvs=4

V3 experimental modal

---

v2/perps-v2/perps-subgraph/generated/schema.ts
v2/perps-v2/perps-subgraph/schema.graphql
v2/perps-v2/perps-subgraph/src/futures.ts
v2/perps-v2/perps-subgraph/src/historical-trade-stats.ts
v2/perps-v2/perps-subgraph/src/position-modified.ts
v2/perps-v2/perps-subgraph/tests/historical-trade-stats.test.ts
v2/perps-v2/perps-subgraph/tests/perpsV2.test.ts

I think this should be right.. Deploying to staging/goerli now

Existing trader fix

---

v3/lib/usePoolData/usePoolData.tsx
v3/ui/src/pages/Pool/MarketSection.cy.tsx

Correct type for updates in period

---

v2/lib/useOptimismLayer1Fee/useOptimismLayer1Fee.ts

Regression from my fallback provider pr

The optimism gas contract lives on optimism

---

v2/perps-v2/ui/src/components/Markets/MarketsTable.tsx
v2/perps-v2/ui/src/components/Markets/MarketsTableLoading.tsx
v2/perps-v2/ui/src/components/Shared/DailyVolumeChange/DailyVolumeChange.tsx
v2/perps-v2/ui/src/components/Shared/DailyVolumeChange/index.tsx
v2/perps-v2/ui/src/components/Shared/index.tsx
v2/perps-v2/ui/src/hooks/useMarkets.ts

markets fix + move column

---

v3/subgraphs/src/marketSnapshotByWeek.ts
v3/subgraphs/tests/marketSnapshotByWeek.test.ts

We should expect timestamp to be in seconds.

---

v2/ui/content/V2Home.tsx

Add banner about bedrock

---

v2/components/CRatioBanner/CRatioBanner.tsx
v2/ui/content/V2Home.tsx

Prepping for bedrock completion

---

v2/components/CRatioBanner/CRatioBanner.tsx
v2/ui/content/V2Home.tsx

* remove banner
* dont show banner if warning and hasClaimed
* log
---------

Prepping for bedrock completion (#909)

---

v2/ui/containers/Connector/config.ts

Reverts Synthetixio/js-monorepo#919

Revert "disable wc for release"

---

v2/components/Burn/Burn.tsx
v2/components/Burn/package.json
v2/lib/formatters/date.ts
v2/lib/formatters/index.ts
v2/lib/formatters/package.json
v2/lib/useMinStakeTime/index.ts
v2/lib/useMinStakeTime/package.json
v2/lib/useMinStakeTime/useMinStakeTime.ts
v2/lib/useSynthetixContracts/index.ts
v2/lib/useSynthetixContracts/useIssuer.ts
yarn.lock

Min stake time

---

v2/perps-v2/ui/src/utils/constants.ts

new markets

---

v2/perps-v2/ui/src/utils/constants.ts

new markets (#931)

---

v2/perps-v2/ui/src/hooks/useMarkets.ts

Markets Data query needs to fetch more items

---

v2/lib/formatters/package.json
v2/lib/formatters/tsconfig.json
v2/lib/useGlobalProvidersWithFallback/package.json
v2/lib/useGlobalProvidersWithFallback/tsconfig.json
v2/lib/useGlobalProvidersWithFallback/useGlobalProvidersWithFallback.tsx

Build for formatters and useGlobal Provider

add packages

---

v2/lib/useClaimableRewards/package.json
v2/lib/useClaimableRewards/useClaimableRewards.ts
v2/lib/useDebtShareDataPeriod/package.json
v2/lib/useDebtShareDataPeriod/useDebtShareDataPeriod.ts
yarn.lock

- Display burn amount when in delegate mode
- Make sure claimable rewards updates as you exit delegate mode

Delegate mode fixes

---

v2/ui/content/BridgePage.tsx

Disable bridge

---

v2/ui/components/NativeBridge/ReviewWithdrawModal.tsx
v2/ui/hooks/useCustomGasOptions.ts
v2/ui/hooks/useEstimateFinalizeWithdraw.ts
v2/ui/hooks/useEstimateProveWithdraw.ts
v2/ui/translations/en.json

Add warning gas when finalize withdrawal

---

v2/components/CRatioHealthCard/CRatioHealthCard.tsx
v2/components/CRatioHealthCard/package.json
v2/components/EarnStats/EarnStats.tsx
v2/components/MainActionCards/MainActionCards.cy.tsx
v2/components/MainActionCards/MainActionCards.tsx
v2/components/WalletBalances/TableComponents.tsx
v2/components/WalletBalances/WalletBalances.tsx
v2/lib/Constants/links.ts
v2/lib/useSynthRedeemer/package.json
v2/lib/useSynthRedeemer/useSynthRedeemer.ts
v2/lib/useSynthsBalances/useSynthsBalances.ts
v2/ui/translations/en.json
yarn.lock

=> Multiply balance by discount
=> Add tooltip to explain

call out redemption amount

---

v2/components/Navigation/Navigation.tsx
v2/components/UserBalances/UserBalances.tsx
v2/components/UtilityCard/UtilityCard.stories.tsx
v2/lib/Constants/links.ts
v2/ui/App.tsx
v2/ui/content/TermsPage.tsx
v2/ui/content/V2Terms.tsx
v2/ui/index.html

* Update App.tsx
* Update index.html
* Update UserBalances.tsx
* Update V2Terms.tsx
* Update Navigation.tsx
* Update links.ts
* Apply suggestions from code review
* More changes
---------

Ethlimo to io (#1122)
